<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.weicoder</groupId>
		<artifactId>weicoder</artifactId>
		<version>3.7.1</version>
	</parent>
	<artifactId>gpu</artifactId>
	<name>gpu</name>
	<description>java gpu tools</description>
	<url>https://github.com/wdcode/weicoder/gpu</url>
	<licenses>
		<license>
			<name>木兰公共许可证, 第2版</name>
			<url>http://license.coscl.org.cn/MulanPubL-2.0/</url>
		</license>
	</licenses>
	<developers>
		<developer>
			<name>wdcode</name>
			<email>wdcode@qq.com</email>
		</developer>
	</developers>
	<scm>
		<connection>scm:git@github.com:wdcode/</connection>
		<developerConnection>scm:git@github.com:wdcode</developerConnection>
		<url>git@github.com:wdcode</url>
	</scm>

	<dependencies>
		<dependency>
			<groupId>com.weicoder</groupId>
			<artifactId>common</artifactId>
		</dependency>
		<dependency>
			<groupId>com.aparapi</groupId>
			<artifactId>aparapi</artifactId> 
		</dependency>
		<!-- 
		<dependency>
			<groupId>org.jocl</groupId>
			<artifactId>jocl</artifactId>
			<version>2.0.4</version>
		</dependency>
		<dependency>
			<groupId>org.jocl</groupId>
			<artifactId>jocl-blast</artifactId>
			<version>1.5.2</version>
		</dependency> 
		<dependency>
			<groupId>org.jcuda</groupId>
			<artifactId>jcuda</artifactId>
			<version>11.7.0</version>
		</dependency>
		<dependency>
			<groupId>org.jcuda</groupId>
			<artifactId>jcublas</artifactId>
			<version>11.7.0</version>
		</dependency>
		<dependency>
			<groupId>org.jcuda</groupId>
			<artifactId>jcufft</artifactId>
			<version>11.7.0</version>
		</dependency>
		<dependency>
			<groupId>org.jcuda</groupId>
			<artifactId>jcusparse</artifactId>
			<version>11.7.0</version>
		</dependency>
		<dependency>
			<groupId>org.jcuda</groupId>
			<artifactId>jcusolver</artifactId>
			<version>11.7.0</version>
		</dependency>
		<dependency>
			<groupId>org.jcuda</groupId>
			<artifactId>jcurand</artifactId>
			<version>11.7.0</version>
		</dependency>
		<dependency>
			<groupId>org.jcuda</groupId>
			<artifactId>jcudnn</artifactId>
			<version>11.7.0</version>
		</dependency>
		-->
	</dependencies>
</project>