<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.weicoder</groupId>
		<artifactId>build</artifactId>
		<version>2.8.2</version> 
	</parent>
	<artifactId>weicoder</artifactId>
	<version>3.8.2</version>
	<packaging>pom</packaging>
	<name>weicoder</name>
	<description>java weicoder tools</description>
	<url>https://github.com/wdcode/weicoder</url>
	<licenses>
		<license>
			<name>木兰公共许可证, 第2版</name>
			<url>http://license.coscl.org.cn/MulanPubL-2.0</url>
		</license>
	</licenses>
	<developers>
		<developer>
			<name>wdcode</name>
			<email>wdcode@qq.com</email>
		</developer>
	</developers>
	<scm>
		<connection>scm:git@github.com:wdcode/</connection>
		<developerConnection>scm:git@github.com:wdcode</developerConnection>
		<url>git@github.com:wdcode</url>
	</scm>

	<properties>
		<log4j-core>2.25.4</log4j-core>
		<fastjson2>2.0.61</fastjson2> 
		<hibernate-envers>7.3.2.Final</hibernate-envers>
		<netty-all>4.2.12.Final</netty-all>
		<mongo-java-driver>3.12.14</mongo-java-driver>
		<influxdb-java>2.25</influxdb-java>
		<flink-java>1.20.3</flink-java>
		<jedis>7.4.1</jedis>
		<jsoup>1.22.2</jsoup> 
		<seata>2.6.0</seata>
		<kafka-clients>4.2.0</kafka-clients>
		<sofa-rpc>5.14.2</sofa-rpc>
		<guava>33.6.0-jre</guava>
		<elasticsearch-java>9.3.4</elasticsearch-java>
		<poi>5.5.1</poi>
		<tomcat-embed>11.0.21</tomcat-embed>
		<nacos-client>3.2.1</nacos-client>
		<hadoop-client>3.5.0</hadoop-client>
		<protobuf-java>4.34.1</protobuf-java>
		<httpclient5>5.6.1</httpclient5>
		<okhttp-jvm>5.3.2</okhttp-jvm>
		<HikariCP>7.0.2</HikariCP>
		<solr-solrj>10.0.0</solr-solrj>
		<snakeyaml>2.6</snakeyaml>
		<opencsv>5.12.0</opencsv>
		<druid>1.2.28</druid>
		<shiro>2.1.0</shiro>
		<curator-framework>5.9.0</curator-framework>
		<hbase-client>2.6.5</hbase-client>
		<jackson-databind>2.21.2</jackson-databind> 
		<disruptor>4.0.0</disruptor>
		<commons-compress>1.28.0</commons-compress>
		<aparapi>3.0.2</aparapi>
		<mysql-connector-java>8.0.33</mysql-connector-java>
		<hibernate-core>5.6.15.Final</hibernate-core>
		<xstream>1.4.21</xstream>
		<retrofit>3.0.0</retrofit>
		<dom4j>2.2.0</dom4j>
		<quartz>2.5.2</quartz>
		<commons-email>1.6.0</commons-email>
		<commons-pool2>2.13.1</commons-pool2>
	</properties>

	<modules>
		<module>common</module>
		<module>cache</module>
		<module>csv</module>
		<module>dao</module>
		<module>disruptor</module>
		<module>elasticsearch</module>
		<module>email</module>
		<module>excel</module>
		<module>gpu</module>
		<module>hbase</module>
		<module>httpclient</module>
		<module>http</module>
		<module>html</module>
		<module>hibernate</module>
		<module>image</module>
		<module>json</module>
		<module>kafka</module>
		<module>log4j</module>
		<module>memcache</module>
		<module>mongo</module>
		<module>nacos</module>
		<module>protobuf</module>
		<module>quartz</module>
		<module>redis</module>
		<module>rpc</module>
		<module>socket</module>
		<module>solr</module> 
		<module>shiro</module> 
		<module>tomcat</module>
		<module>web</module>
		<module>websocket</module>
		<module>xml</module>
		<module>yaml</module>
		<module>zookeeper</module>
		<module>zip</module>
		<module>hadoop</module>
		<module>influxdb</module>
		<module>frame</module>
		<module>flink</module>
		<module>seata</module>
	</modules>
 
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>common</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>cache</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>csv</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>dao</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>disruptor</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>elasticsearch</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>email</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>excel</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>gpu</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>hbase</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>httpclient</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>http</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>html</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>hibernate</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>image</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>json</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>kafka</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>log4j</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>memcache</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>mongo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>nacos</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>protobuf</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>quartz</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>redis</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>rpc</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>socket</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>solr</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>shiro</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>tomcat</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>web</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>websocket</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>xml</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>yaml</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>zookeeper</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>zip</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>frame</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>seata</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>influxdb</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>hadoop</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.weicoder</groupId>
				<artifactId>flink</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.google.guava</groupId>
				<artifactId>guava</artifactId>
				<version>${guava}</version>
			</dependency>
			<dependency>
				<groupId>com.opencsv</groupId>
				<artifactId>opencsv</artifactId>
				<version>${opencsv}</version>
			</dependency>
			<dependency>
				<groupId>com.google.protobuf</groupId>
				<artifactId>protobuf-java</artifactId>
				<version>${protobuf-java}</version>
			</dependency>
			<dependency>
				<groupId>io.netty</groupId>
				<artifactId>netty-all</artifactId>
				<version>${netty-all}</version>
			</dependency>
			<dependency>
				<groupId>com.alibaba.nacos</groupId>
				<artifactId>nacos-client</artifactId>
				<version>${nacos-client}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.hadoop</groupId>
				<artifactId>hadoop-client</artifactId>
				<version>${hadoop-client}</version>
			</dependency>
			<dependency>
				<groupId>org.mongodb</groupId>
				<artifactId>mongo-java-driver</artifactId>
				<version>${mongo-java-driver}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-api</artifactId>
				<version>${log4j-core}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-core</artifactId>
				<version>${log4j-core}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-slf4j-impl</artifactId>
				<version>${log4j-core}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.kafka</groupId>
				<artifactId>kafka-clients</artifactId>
				<version>${kafka-clients}</version>
			</dependency> 
			<dependency>
				<groupId>com.alibaba.fastjson2</groupId>
				<artifactId>fastjson2</artifactId>
				<version>${fastjson2}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.httpcomponents.client5</groupId>
				<artifactId>httpclient5</artifactId>
				<version>${httpclient5}</version>
			</dependency>
			<dependency>
				<groupId>com.squareup.okhttp3</groupId>
    			<artifactId>okhttp-jvm</artifactId> 
				<version>${okhttp-jvm}</version>
			</dependency>
			<dependency>
				<groupId>com.squareup.retrofit2</groupId>
				<artifactId>retrofit</artifactId>
				<version>${retrofit}</version>
			</dependency>
			<dependency>
				<groupId>org.hibernate.orm</groupId>
				<artifactId>hibernate-envers</artifactId>
				<version>${hibernate-envers}</version>
			</dependency>
			<dependency>
				<groupId>org.hibernate.orm</groupId>
				<artifactId>hibernate-hikaricp</artifactId>
				<version>${hibernate-envers}</version>
			</dependency>
			<dependency>
				<groupId>org.hibernate</groupId>
				<artifactId>hibernate-core</artifactId>
				<version>${hibernate-core}</version>
			</dependency>
			<dependency>
				<groupId>org.hibernate</groupId>
				<artifactId>hibernate-hikaricp</artifactId>
				<version>${hibernate-core}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.hbase</groupId>
				<artifactId>hbase-client</artifactId>
				<version>${hbase-client}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.poi</groupId>
				<artifactId>poi-ooxml</artifactId>
				<version>${poi}</version>
			</dependency>
			<dependency>
				<groupId>co.elastic.clients</groupId>
				<artifactId>elasticsearch-java</artifactId>
				<version>${elasticsearch-java}</version>
			</dependency>
			<dependency>
				<groupId>com.fasterxml.jackson.core</groupId>
				<artifactId>jackson-databind</artifactId>
				<version>${jackson-databind}</version>
			</dependency>
			<dependency>
				<groupId>com.zaxxer</groupId>
				<artifactId>HikariCP</artifactId>
				<version>${HikariCP}</version>
			</dependency>
			<dependency>
				<groupId>mysql</groupId>
				<artifactId>mysql-connector-java</artifactId>
				<version>${mysql-connector-java}</version>
			</dependency>
			<dependency>
				<groupId>redis.clients</groupId>
				<artifactId>jedis</artifactId>
				<version>${jedis}</version>
			</dependency>
			<dependency>
				<groupId>com.alipay.sofa</groupId>
				<artifactId>sofa-rpc-all</artifactId>
				<version>${sofa-rpc}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.solr</groupId>
				<artifactId>solr-solrj</artifactId>
				<version>${solr-solrj}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.tomcat.embed</groupId>
				<artifactId>tomcat-embed-core</artifactId>
				<version>${tomcat-embed}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.tomcat.embed</groupId>
				<artifactId>tomcat-embed-jasper</artifactId>
				<version>${tomcat-embed}</version>
			</dependency>
			<dependency>
				<groupId>com.thoughtworks.xstream</groupId>
				<artifactId>xstream</artifactId>
				<version>${xstream}</version>
			</dependency>
			<dependency>
				<groupId>org.yaml</groupId>
				<artifactId>snakeyaml</artifactId>
				<version>${snakeyaml}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-compress</artifactId>
				<version>${commons-compress}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.curator</groupId>
				<artifactId>curator-framework</artifactId>
				<version>${curator-framework}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.curator</groupId>
				<artifactId>curator-recipes</artifactId>
				<version>${curator-framework}</version>
			</dependency>
			<dependency>
				<groupId>org.influxdb</groupId>
				<artifactId>influxdb-java</artifactId>
				<version>${influxdb-java}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.flink</groupId>
				<artifactId>flink-clients</artifactId>
				<version>${flink-java}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.seata</groupId>
				<artifactId>seata-tm</artifactId>
				<version>${seata}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.seata</groupId>
				<artifactId>seata-rm-datasource</artifactId>
				<version>${seata}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.seata</groupId>
				<artifactId>seata-serializer-seata</artifactId>
				<version>${seata}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.seata</groupId>
				<artifactId>seata-sqlparser-druid</artifactId>
				<version>${seata}</version>
			</dependency>
			<dependency>
				<groupId>com.alibaba</groupId>
				<artifactId>druid</artifactId>
				<version>${druid}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.shiro</groupId>
				<artifactId>shiro-core</artifactId>
				<version>${shiro}</version>
			</dependency>
			<dependency>
				<groupId>com.lmax</groupId>
				<artifactId>disruptor</artifactId>
				<version>${disruptor}</version>
			</dependency>
			<dependency>
				<groupId>org.jsoup</groupId>
				<artifactId>jsoup</artifactId>
				<version>${jsoup}</version>
			</dependency>
			<dependency>
				<groupId>com.aparapi</groupId>
				<artifactId>aparapi</artifactId>
				<version>${aparapi}</version>
			</dependency>
			<dependency>
				<groupId>org.dom4j</groupId>
				<artifactId>dom4j</artifactId>
				<version>${dom4j}</version>
			</dependency>
			<dependency>
				<groupId>org.quartz-scheduler</groupId>
				<artifactId>quartz</artifactId>
				<version>${quartz}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-email</artifactId>
				<version>${commons-email}</version>
			</dependency>
			<dependency>
			  <groupId>org.apache.commons</groupId>
			  <artifactId>commons-pool2</artifactId>
			  <version>${commons-pool2}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
</project>