-- MySQL Script generated by MySQL Workbench
-- Wed Jan  3 11:32:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema back
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema back
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `back` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `back` ;

-- -----------------------------------------------------
-- Table `back`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL COMMENT '用户名',
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `password` CHAR(40) NULL DEFAULT NULL COMMENT '用户密码',
  `state` TINYINT NULL DEFAULT 1 COMMENT 'Email',
  `ip` CHAR(15) NULL DEFAULT NULL,
  `time` INT NULL DEFAULT 0,
  `role_id` INT NULL DEFAULT NULL COMMENT '用户状态 0 无效 1 有效 2 已删除',
  `login_ip` CHAR(15) NULL DEFAULT NULL,
  `login_time` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Index_Name` (`name` ASC));


-- -----------------------------------------------------
-- Table `back`.`authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back`.`authority` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `authority` VARCHAR(50) NULL DEFAULT NULL COMMENT '角色名',
  `name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MYISAM;


-- -----------------------------------------------------
-- Table `back`.`logs_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back`.`logs_login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `ip` CHAR(15) NULL DEFAULT NULL,
  `time` INT NULL DEFAULT NULL,
  `state` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `Index_Date` (`time` ASC));


-- -----------------------------------------------------
-- Table `back`.`logs_operate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back`.`logs_operate` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL COMMENT '用户主键',
  `time` INT NULL DEFAULT NULL COMMENT '操作时间',
  `content` TEXT NULL DEFAULT NULL,
  `state` TINYINT NULL DEFAULT NULL,
  `ip` CHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `Index_Date` (`time` ASC));


-- -----------------------------------------------------
-- Table `back`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back`.`menu` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(50) NULL DEFAULT NULL COMMENT '菜单名',
  `menu_id` INT NULL DEFAULT 0,
  `url` VARCHAR(100) NULL DEFAULT NULL,
  `type` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `back`.`operate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back`.`operate` (
  `link` VARCHAR(50) NOT NULL COMMENT '操作连接',
  `name` VARCHAR(50) NULL DEFAULT NULL COMMENT '操作名称 用于显示',
  `type` INT NULL DEFAULT NULL,
  PRIMARY KEY (`link`),
  INDEX `Index_ID` (`link` ASC));


-- -----------------------------------------------------
-- Table `back`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(50) NULL DEFAULT NULL COMMENT '角色名',
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `back`.`role_authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back`.`role_authority` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `authority_id` INT NULL DEFAULT 0,
  `role_id` INT NULL DEFAULT 0 COMMENT '角色ID',
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `back`.`role_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back`.`role_menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NULL DEFAULT NULL,
  `menu_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `Index_Menu` (`menu_id` ASC));


-- -----------------------------------------------------
-- Table `back`.`role_operate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `back`.`role_operate` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `operate` VARCHAR(50) NULL DEFAULT '0',
  `role_id` INT NULL DEFAULT 0 COMMENT '角色ID',
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
