<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<groupId>com.weicoder</groupId>
		<artifactId>weicoder</artifactId>
		<version>3.7.1</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>redis</artifactId>
	<name>redis</name>
	<description>java redis tools</description>
	<url>https://github.com/wdcode/weicoder/redis</url>
	<licenses>
		<license>
			<name>木兰公共许可证, 第2版</name>
			<url>http://license.coscl.org.cn/MulanPubL-2.0/</url>
		</license>
	</licenses>
	<developers>
		<developer>
			<name>wdcode</name>
			<email>wdcode@qq.com</email>
		</developer>
	</developers>
	<scm>
		<connection>scm:git@github.com:wdcode/</connection>
		<developerConnection>scm:git@github.com:wdcode</developerConnection>
		<url>git@github.com:wdcode</url>
	</scm>

	<dependencies>
		<dependency>
			<groupId>com.weicoder</groupId>
			<artifactId>common</artifactId>
		</dependency>
		<dependency>
			<groupId>com.weicoder</groupId>
			<artifactId>cache</artifactId>
		</dependency>
		<dependency>
			<groupId>com.weicoder</groupId>
			<artifactId>json</artifactId>
		</dependency>
		<dependency>
			<groupId>redis.clients</groupId>
			<artifactId>jedis</artifactId>
		</dependency>
		<dependency>
			<groupId>com.weicoder</groupId>
			<artifactId>dao</artifactId>
			<optional>true</optional>
		</dependency> 
	</dependencies>
</project>